# Generated by Django 4.1.3 on 2023-09-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft_api', '0005_remove_nft_wallet_delete_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xrpl_model',
            old_name='user_id',
            new_name='user',
        ),
    ]
