# Generated by Django 4.2.5 on 2023-10-04 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_api', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrpl_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
